In [219]:
import numpy as np

In [220]:
import pandas as pd

In [ ]:
from numpy import genfromtxt

In [167]:
data=pd.read_csv('pedigree2.txt', sep='\t') #wczytanie danych pedigree

In [170]:
data=data.as_matrix()

In [193]:
len(data[:,1])


200

In [215]:
def MacierzSpokrewnien(s, d):
    if len(s) != len(d):
        stop("Length of sire oraz dtam vectors is different")
    else:
        n = len(s)
        N = n + 1
        A = np.zeros((N,N))
        s = (s == 0.0)*(N) + s
        d = (d == 0.0)*N + d
        for i in range(n):
            A[i][i] = 1 + A[s[i]][d[i]]/2.0
            for j in (i+1,n):
                if (j > n-1):
                    break
                A[i][j] = (A[i][s[j]] + A[i][d[j]])/2.0
                A[j][i] = A[i][j] 
              
        return(A)
       

In [216]:
A=MacierzSpokrewnien(data[:,1],data[:,2])

In [218]:
A

array([[ 1. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0.5, ...,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. , ...,  0. ,  0. ,  0. ],
       ..., 
       [ 0. ,  0. ,  0. , ...,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [102]:
L = np.zeros((3,3))

In [103]:
for i in range(3):
    for j in range(3):
        L[i][j]=i*j+i+j

In [104]:
L

array([[ 0.,  1.,  2.],
       [ 1.,  3.,  5.],
       [ 2.,  5.,  8.]])

In [105]:
L/2

array([[ 0. ,  0.5,  1. ],
       [ 0.5,  1.5,  2.5],
       [ 1. ,  2.5,  4. ]])

In [135]:
(L[2][2] + L[2][1])/2

6.5

In [191]:
L[:,1]

array([ 1.,  3.,  5.])