In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
from numpy import genfromtxt

In [6]:
data=pd.read_csv('pedigree2.txt', sep='\t') #wczytanie danych pedigree

In [7]:
data=data.as_matrix()

In [143]:
data[5][0]

111

In [140]:
def MacierzSpokrewnien(s, d):
    if len(s) != len(d):
        stop("Length of sire oraz dtam vectors is different")
    else:
        n = len(s)
        N = n + 1
        A = np.zeros((N,N))
        s = (s == 0.0)* (N) + s
        d = (d == 0.0)* N + d
        for i in range(n):
            print(s[i],d[i],A[s[i]][d[i]])
            A[i][i] = 1.0 + A[s[i]][d[i]]/2.0
            for j in (i+1,n):
                if (j >= n):
                    break
                A[i][j] = (A[i][s[j]] + A[i][d[j]])/2.0
                A[j][i] = A[i][j] 
              
        return(A)
       

In [141]:
A=MacierzSpokrewnien(data[:,1],data[:,2])

5 82 0.0
1 15 0.0
1 97 0.0
3 99 0.0
4 88 0.0
4 15 0.0
5 43 0.0
5 90 0.0
1 38 0.0
1 20 0.0
5 98 0.0
4 66 0.0
3 74 0.0
1 81 0.0
3 101 0.0
3 81 0.0
2 96 0.0
2 14 0.0
2 82 0.0
3 15 0.0
5 101 0.0
5 92 0.0
1 20 0.0
2 89 0.0
4 31 0.0
5 54 0.0
5 18 0.0
2 19 0.0
3 64 0.0
1 9 0.0
4 101 0.0
4 101 0.0
4 80 0.0
3 104 0.0
3 102 0.0
1 104 0.0
1 69 0.0
3 16 0.0
3 53 0.0
4 30 0.0
3 29 0.0
5 22 0.0
5 17 0.0
5 57 0.0
5 10 0.0
4 36 0.0
2 96 0.0
1 10 0.0
2 90 0.0
5 50 0.0
1 13 0.0
5 98 0.0
2 92 0.0
1 98 0.0
4 50 0.0
1 66 0.0
5 61 0.0
4 34 0.0
2 9 0.0
2 72 0.0
1 105 0.0
4 50 0.0
3 21 0.0
1 25 0.0
2 35 0.0
2 31 0.0
3 11 0.0
5 29 0.0
4 20 0.0
5 92 0.0
4 104 0.0
1 53 0.0
3 88 0.0
2 82 0.0
5 8 0.0
3 79 0.0
5 84 0.0
4 93 0.0
2 103 0.0
5 100 0.0
4 35 0.0
4 76 0.0
4 67 0.0
4 16 0.0
3 51 0.0
1 26 0.0
4 35 0.0
4 84 0.0
1 25 0.0
5 55 0.0
1 94 0.0
4 13 0.0
2 97 0.0
5 30 0.0
4 54 0.0
5 52 0.0
2 31 0.0
4 65 0.0
2 77 0.0
2 28 0.0
3 91 0.0
3 104 0.0
3 20 0.0
2 61 0.0
2 22 0.0
2 21 0.0
5 21 0.0
1 6 0.0
1 59 0.0
2 66 0.0
4 

In [142]:
A

array([[ 1. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0.5, ...,  0. ,  0. ,  0. ],
       [ 0. ,  0.5,  1. , ...,  0. ,  0. ,  0. ],
       ..., 
       [ 0. ,  0. ,  0. , ...,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]])

In [152]:
def RelMatrix(macierz):
    x = macierz[0,0]
    length1=len(macierz)
    while x>1:
        x = x-1
        y = np.array([x,0,0])
        macierz = np.row_stack((y,macierz))
    length = len(macierz)
    matrix = np.zeros((length,length))
    for i in range(length):
        for j in range(length):
            ojciec = macierz[j,1]
            matka = macierz[j,2]
            if i==j:
                if ojciec == 0 or matka == 0:
                    matrix[j,i] = 1.
                else:
                    print(ojciec, matka, matrix[ojciec,matka])
                    matrix[j,i] = 1. + matrix[ojciec,matka]*0.5
            else:
                if ojciec!=0:
                    ojciec = matrix[i,macierz[j,1]]
                if matka!=0:
                    matka = matrix[i,macierz[j,2]]
                matrix[i,j] = 0.5 * (ojciec+matka)
        for x in range(length):
            matrix[x,i] = matrix[i,x]
    return(matrix)
                    

In [153]:
matrix = RelMatrix(data)

5 82 0.0
1 15 0.0
1 97 0.0
3 99 0.0
4 88 0.0
4 15 0.0
5 43 0.0
5 90 0.0
1 38 0.0
1 20 0.0
5 98 0.0
4 66 0.0
3 74 0.0
1 81 0.0
3 101 0.0
3 81 0.0
2 96 0.0
2 14 0.0
2 82 0.0
3 15 0.0
5 101 0.0
5 92 0.0
1 20 0.0
2 89 0.0
4 31 0.0
5 54 0.0
5 18 0.0
2 19 0.0
3 64 0.0
1 9 0.0
4 101 0.0
4 101 0.0
4 80 0.0
3 104 0.0
3 102 0.0
1 104 0.0
1 69 0.0
3 16 0.0
3 53 0.0
4 30 0.0
3 29 0.0
5 22 0.0
5 17 0.0
5 57 0.0
5 10 0.0
4 36 0.0
2 96 0.0
1 10 0.0
2 90 0.0
5 50 0.0
1 13 0.0
5 98 0.0
2 92 0.0
1 98 0.0
4 50 0.0
1 66 0.0
5 61 0.0
4 34 0.0
2 9 0.0
2 72 0.0
1 105 0.0
4 50 0.0
3 21 0.0
1 25 0.0
2 35 0.0
2 31 0.0
3 11 0.0
5 29 0.0
4 20 0.0
5 92 0.0
4 104 0.0
1 53 0.0
3 88 0.0
2 82 0.0
5 8 0.0
3 79 0.0
5 84 0.0
4 93 0.0
2 103 0.0
5 100 0.0
4 35 0.0
4 76 0.0
4 67 0.0
4 16 0.0
3 51 0.0
1 26 0.0
4 35 0.0
4 84 0.0
1 25 0.0
5 55 0.0
1 94 0.0
4 13 0.0
2 97 0.0
5 30 0.0
4 54 0.0
5 52 0.0
2 31 0.0
4 65 0.0
2 77 0.0
2 28 0.0
3 91 0.0
3 104 0.0
3 20 0.0
2 61 0.0
2 22 0.0
2 21 0.0
5 21 0.0
1 6 0.0
1 59 0.0
2 66 0.0
4 

In [155]:
matrix

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [89]:
data

array([[106,   5,  82],
       [107,   1,  15],
       [108,   1,  97],
       [109,   3,  99],
       [110,   4,  88],
       [111,   4,  15],
       [112,   5,  43],
       [113,   5,  90],
       [114,   1,  38],
       [115,   1,  20],
       [116,   5,  98],
       [117,   4,  66],
       [118,   3,  74],
       [119,   1,  81],
       [120,   3, 101],
       [121,   3,  81],
       [122,   2,  96],
       [123,   2,  14],
       [124,   2,  82],
       [125,   3,  15],
       [126,   5, 101],
       [127,   5,  92],
       [128,   1,  20],
       [129,   2,  89],
       [130,   4,  31],
       [131,   5,  54],
       [132,   5,  18],
       [133,   2,  19],
       [134,   3,  64],
       [135,   1,   9],
       [136,   4, 101],
       [137,   4, 101],
       [138,   4,  80],
       [139,   3, 104],
       [140,   3, 102],
       [141,   1, 104],
       [142,   1,  69],
       [143,   3,  16],
       [144,   3,  53],
       [145,   4,  30],
       [146,   3,  29],
       [147,   5

In [135]:
(L[2][2] + L[2][1])/2

6.5

In [191]:
L[:,1]

array([ 1.,  3.,  5.])